BASICS OF NLP



NEED TO UNDERSTAND FIRST

sklearn(manifold."TSNE") AND sklearn(decomposition."PCA") CAN BE USED FOR DIMENSIONALITY REDUCTION 

In [1]:
import spacy 
import re 
from spacy.lang.en.stop_words import STOP_WORDS
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import torch 
import torch.nn as nn 
import torch.optim as optim 
import numpy as np
import transformers
import torchtext
from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder
from sklearn.manifold import TSNE
import nltk 
from nltk.tokenize import word_tokenize
nltk.download('punkt')

c:\Users\Kousimon\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Kousimon\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [2]:
nlp = spacy.load("en_core_web_sm")
text =  "Koushick is %#@$%##% learning Natural!@$@#$@# Language Processing from ChatGPT."
Cleaned_words = re.sub(r'[^a-zA-Z0-9\s]'," ",text)
cleaned_txt = Cleaned_words.lower()

In [3]:
doc = nlp(cleaned_txt)

filtered_tokens = []

print("Tokens:")
for token in doc:
    if token.text not in STOP_WORDS and not token.is_punct:
        print(token.text)

Tokens:
koushick
         
learning
natural
        
language
processing
chatgpt


In [4]:
print("Part of Speech Tags")

for token in doc:
    print(f'{token.text} -> {token.pos_}')


Part of Speech Tags
koushick -> PROPN
is -> AUX
          -> SPACE
learning -> VERB
natural -> ADJ
         -> SPACE
language -> NOUN
processing -> NOUN
from -> ADP
chatgpt -> NOUN


In [5]:
## Vectorizing
## BAG OF WORDS 

from sklearn.feature_extraction.text import CountVectorizer

# Sample corpus
docs = [
    "NLP is fun and exciting",
    "ChatGPT makes NLP more fun",
    "I love learning NLP"
]

# Create vectorizer
vectorizer = CountVectorizer()

# Fit and transform the corpus
X = vectorizer.fit_transform(docs)

# Get vocabulary
print("Vocabulary:\n", vectorizer.get_feature_names_out())

# Show BoW Matrix
print("\nBag of Words Matrix:")
print(X.toarray())

Vocabulary:
 ['and' 'chatgpt' 'exciting' 'fun' 'is' 'learning' 'love' 'makes' 'more'
 'nlp']

Bag of Words Matrix:
[[1 0 1 1 1 0 0 0 0 1]
 [0 1 0 1 0 0 0 1 1 1]
 [0 0 0 0 0 1 1 0 0 1]]


In [6]:
## Vectorizing
## TERM FREQUENCY INVERSE DOCUMENT FREQUENCY (TF-IDF)
docs = [
    "NLP is fun and exciting",
    "ChatGPT makes NLP more fun",
    "I love learning NLP"
]

# Create TF-IDF vectorizer
tfidf = TfidfVectorizer()

# Fit and transform
X = tfidf.fit_transform(docs)

# Get vocabulary
print("Vocabulary:\n", tfidf.get_feature_names_out())

# Show TF-IDF Matrix
print("\nTF-IDF Matrix:")
print(X.toarray())

Vocabulary:
 ['and' 'chatgpt' 'exciting' 'fun' 'is' 'learning' 'love' 'makes' 'more'
 'nlp']

TF-IDF Matrix:
[[0.50461134 0.         0.50461134 0.38376993 0.50461134 0.
  0.         0.         0.         0.29803159]
 [0.         0.50461134 0.         0.38376993 0.         0.
  0.         0.50461134 0.50461134 0.29803159]
 [0.         0.         0.         0.         0.         0.65249088
  0.65249088 0.         0.         0.38537163]]


In [ ]:
tokens

['nlp', 'is', 'fun', 'and', 'powerful', 'than', 'other', 'field', 'of', 'nlp']

In [ ]:
vocab

['and', 'field', 'fun', 'is', 'nlp', 'of', 'other', 'powerful', 'than']

In [ ]:
word2idx

{'and': 0,
 'field': 1,
 'fun': 2,
 'is': 3,
 'nlp': 4,
 'of': 5,
 'other': 6,
 'powerful': 7,
 'than': 8}

In [ ]:
def one_hot_encoding(word,vocab):
    vector = [0]*len(vocab)
    idx = word2idx[word]
    vector[idx] = 1
    return vector

for word in tokens:
    print(f'{word:10} -> {one_hot_encoding(word,vocab)}')

nlp        -> [0, 0, 0, 0, 1, 0, 0, 0, 0]
is         -> [0, 0, 0, 1, 0, 0, 0, 0, 0]
fun        -> [0, 0, 1, 0, 0, 0, 0, 0, 0]
and        -> [1, 0, 0, 0, 0, 0, 0, 0, 0]
powerful   -> [0, 0, 0, 0, 0, 0, 0, 1, 0]
than       -> [0, 0, 0, 0, 0, 0, 0, 0, 1]
other      -> [0, 0, 0, 0, 0, 0, 1, 0, 0]
field      -> [0, 1, 0, 0, 0, 0, 0, 0, 0]
of         -> [0, 0, 0, 0, 0, 1, 0, 0, 0]
nlp        -> [0, 0, 0, 0, 1, 0, 0, 0, 0]


In [ ]:
## BAG OF WORDS

In [ ]:
## Checking whether the cleaned text is empty or not  (IF NEEDED PURPOSE ONLY)
clean = re.sub(r'[^a-zA-Z\s]', "", "@2025!")
print(repr(clean))

In [ ]:
sentences = [
    "I love NLP!",
    "NLP is powerful 100%.",
    "Welcome to NLP @2025!"
]

tokenized = [re.sub(r'[^a-zA-Z\s]', "", sent).lower().split() for sent in sentences]

tokenized

[['i', 'love', 'nlp'], ['nlp', 'is', 'powerful'], ['welcome', 'to', 'nlp']]

In [ ]:
vocab = sorted(set(word for sent in tokenized for word in sent))
Word2idx = {word:idx for word,idx in enumerate(vocab)}


In [ ]:
vocab

['i', 'is', 'love', 'nlp', 'powerful', 'to', 'welcome']

In [ ]:
Word2idx

{0: 'i', 1: 'is', 2: 'love', 3: 'nlp', 4: 'powerful', 5: 'to', 6: 'welcome'}

In [ ]:
vocab

['100%.',
 '@2025!',
 'i',
 'is',
 'love',
 'nlp',
 'nlp!',
 'powerful',
 'to',
 'welcome']

In [ ]:
Word2idx

{0: '100%.',
 1: '@2025!',
 2: 'i',
 3: 'is',
 4: 'love',
 5: 'nlp',
 6: 'nlp!',
 7: 'powerful',
 8: 'to',
 9: 'welcome'}

In [ ]:
sentences = [
    "I love natural language processing.",
    "NLP is a branch of artificial intelligence.",
    "Deep learning models perform well on text data.",
    "Transformers have revolutionized NLP.",
    "Word embeddings capture semantic meaning."
]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
import pandas as pd
import torch
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')

# Load your CSV file
df = pd.read_csv("nlp_sentences_50.csv")
sentences = df["text"].astype(str).tolist()

# Tokenize
tokenized = [word_tokenize(s.lower()) for s in sentences]


In [ ]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Flatten and encode
vocab = sorted(set(word for sent in tokenized for word in sent))
word2idx = {w: i for i, w in enumerate(vocab)}
vocab_size = len(word2idx)

# One-hot encode all words
def one_hot_encode(tokens, vocab_size, word2idx):
    return [np.eye(vocab_size)[word2idx[word]] for word in tokens if word in word2idx]

one_hot_sentences = [one_hot_encode(sent, vocab_size, word2idx) for sent in tokenized]

print("Sample one-hot vector (word-level):", one_hot_sentences[0][0])


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Recombine tokens for BoW
rejoined = [' '.join(tokens) for tokens in tokenized]
vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform(rejoined).toarray()

print("BoW shape:", bow_matrix.shape)
print("Sample BoW vector:", bow_matrix[0])


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(rejoined).toarray()

print("TF-IDF shape:", tfidf_matrix.shape)
print("Sample TF-IDF vector:", tfidf_matrix[0])


In [ ]:
import torch.nn as nn

embedding_dim = 50
word_embedding = nn.Embedding(vocab_size, embedding_dim)

# Convert sentences to word indices
indexed = [[word2idx[word] for word in sent if word in word2idx] for sent in tokenized]

# Embed each sentence
sentence_vectors = []
for idx_list in indexed:
    idx_tensor = torch.tensor(idx_list)
    embeddings = word_embedding(idx_tensor)
    sentence_embedding = embeddings.mean(dim=0)
    sentence_vectors.append(sentence_embedding)

sentence_vectors = torch.stack(sentence_vectors)
print("Random embedding vector shape:", sentence_vectors.shape)
print("Sample embedding vector:", sentence_vectors[0])


In [ ]:
from torchtext.vocab import GloVe

# Load GloVe 100D
glove = GloVe(name='6B', dim=100)

# For each tokenized sentence, convert each word to glove vector, then average
glove_sentences = []
for tokens in tokenized:
    vectors = []
    for word in tokens:
        if word in glove.stoi:
            vectors.append(glove[word])
        else:
            vectors.append(torch.zeros(100))  # Unknown words
    if vectors:
        avg_vec = torch.stack(vectors).mean(dim=0)
    else:
        avg_vec = torch.zeros(100)
    glove_sentences.append(avg_vec)

glove_sentences = torch.stack(glove_sentences)

print("GloVe sentence vector shape:", glove_sentences.shape)
print("Sample GloVe sentence vector:", glove_sentences[0])


In [ ]:
from transformers import BertTokenizer, BertModel
import torch
from tqdm import tqdm

# Load pre-trained BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
bert_model = BertModel.from_pretrained("bert-base-uncased")
bert_model.eval()  # Set to evaluation mode

# Get BERT sentence embeddings
bert_sentence_embeddings = []

for sentence in tqdm(sentences, desc="Generating BERT embeddings"):
    with torch.no_grad():
        inputs = tokenizer(sentence, return_tensors='pt', truncation=True, padding='max_length', max_length=50)
        outputs = bert_model(**inputs)
        cls_embedding = outputs.last_hidden_state[0, 0, :]  # [CLS] token representation
        bert_sentence_embeddings.append(cls_embedding)

bert_sentence_embeddings = torch.stack(bert_sentence_embeddings)
print("BERT embeddings shape:", bert_sentence_embeddings.shape)
print("Sample BERT vector:", bert_sentence_embeddings[0])
